broadcast_address = "10.1.0.19"
http_address = "0.0.0.0:4151"
tcp_address = "0.0.0.0:4150"
mem_queue_size = 10000
msg_timeout = "1000s"
max_msg_timeout = "1h"
max_rdy_count = 10000
max_output_buffer_size = 1024000
max_msg_size = 10485760
max_body_size = 198098920
data_path="/opt/nsq/data"
nsqlookupd_tcp_addresses = [
    "10.5.0.4:4160",
    "10.5.0.17:4160",
    "10.5.0.7:4160"
]
